### ISSUE TITLE
[Bug] Open URI's from the chat message

### ISSUE THREAD

**Issue by kirilllapshev** [molteo-engineering-team/Dash-Chat-2#28] opened 2022-09-26 20:38 UTC
**Describe the bug**

When a message contains an uri, i get a ERR_UNKNOWN_URL_SCHEME

**To Reproduce**

Send a message containing a link and open it up!

**Expected behavior**

Open a dynamic link and redirect to another screen

**Screenshots**

https://user-images.githubusercontent.com/63013314/192375206-c8c325bc-8138-4569-be3d-2d6bd8de85e5.mov

**Environment**

 - OS: iOS, Android

**Comment by SebastienBtr** [comment] 2022-10-03 12:44
Interesting, regular links work fine. It seems to be an issue with dynamic links (deeplinks).

I am able to reproduce it and I found that `url_launcher` has different launchModes, `LaunchMode.externalApplication` seems to solve the issue.

Next version will have this change, let me know in case the issue remains after that

**Comment by SebastienBtr** [comment] 2022-10-03 12:46
Fixed by #3e4e819c59ff2fa32bfc41a302316fcf7600427e

**Closed by SebastienBtr** 2022-10-03 12:46 UTC
Labels: bug
